server:
  port: 8888
# Oracle Connect
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: scott
    password: tiger

# jpa Setting
  jpa:
    show-sql: true
    hibernate:
    ddl-auto: create

        
